freeEnergy:
    eta: !!float 0.01
    Niter: !!int 2
    J: !!int 5
    M: !!int 3
    filters: 
        - "dh"
        - "dv"

axequalsbSolver:
    algorithm: "conjugateGradient"
    epsilon: !!float 0.00001

deconvolution:
    algorithm: "Sobolev"
    sobolev:
        lambda: !!float 0.000000005
    l2:
        lambda: !!float 0.005
    
filters:
    dh: [[0, 0, 0], [0, -1, 1], [0, 0, 0]]
    dv: [[0, 0, 0], [0, -1, 0], [0, 1, 0]]
    delta: [[0, 0, 0], [0, 1, 0], [0, 0, 0]]
    
paths:
    image: "data/image.jpg"

render:
    maxwidth: !!int 300
    
verbose: True