freeEnergy:
    eta: !!float 0.01
    Niter: !!int 5
    M: !!int 3
    filters: 
        - "dh"
        - "dv"
        
    ivars: [0.70216804986 ,  0.047184142102,   0.004184820868]   #FROM SOURCE CODE
    pis: [0.30471011, 0.43436355, 0.26092634]              #FROM SOURCE CODE

axequalsbSolver:
    algorithm: "conjugateGradient"
    epsilon: !!float 0.0000001
    maxite: !!int 200

deconvolution:
    algorithm: "Sobolev"
    sobolev:
        lambda: !!float 0.000000005
    l2:
        lambda: !!float 0.005
    
derivativefilters:
    dh: [[0, 0, 0], [0, -1, 1], [0, 0, 0]]
    dv: [[0, 0, 0], [0, -1, 0], [0, 1, 0]]
    
paths:
    image: "data/image.jpg"

render:
    maxwidth: !!int 300
    
verbose: True