freeEnergy:
    eta: !!float 0.05
    Niter: !!int 10
    M: !!int 5
    filters: 
        - "dh"
        - "dv"
        
    use_prev_x: False
        
    ivars: [7021.6804986 ,  471.84142102,   41.84820868]   #FROM SOURCE CODE
    pis: [0.30471011, 0.43436355, 0.26092634]              #FROM SOURCE CODE

axequalsbSolver:
    algorithm: "conjugateGradient"
    epsilon: !!float 0.00000001
    maxite: !!int 20000

deconvolution:
    algorithm: "Sobolev"
    sobolev:
        lambda: !!float 0.000000005
    l2:
        lambda: !!float 0.005
    
derivativefilters:
    dh: [[0, 0, 0], [0, -1, 1], [0, 0, 0]]
    dv: [[0, 0, 0], [0, -1, 0], [0, 1, 0]]
    
paths:
    image: "../data/image_1.jpg"

render:
    maxwidth: !!int 300
    
verbose: True